const jobs = [
  {
    id: 1,
    logo: "https://i.pinimg.com/originals/01/ca/da/01cada77a0a7d326d85b7969fe26a728.jpg",
    company: "Amazon",
    datePosted: "5 days ago",
    title: "Senior UI/UX Designer",
    type: "Part-Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    company: "Google",
    datePosted: "2 days ago",
    title: "Frontend Developer",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$95/hr",
    location: "Bangalore, India",
  },
  {
    id: 3,
    logo: "https://seekvectors.com/storage/images/Microsoft-02.jpg",
    company: "Microsoft",
    datePosted: "1 day ago",
    title: "Backend Engineer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$110/hr",
    location: "Hyderabad, India",
  },
  {
    id: 4,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    company: "Netflix",
    datePosted: "4 days ago",
    title: "Product Designer",
    type: "Contract",
    level: "Junior Level",
    salary: "$80/hr",
    location: "Remote",
  },
  {
    id: 5,
    logo: "https://tse2.mm.bing.net/th/id/OIP.zGFQ5tc78-r1JnyfhA5usQHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain&o=7&rm=3",
    company: "Adobe",
    datePosted: "3 days ago",
    title: "Software Engineer",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$100/hr",
    location: "Pune, India",
  },
  {
    id: 6,
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    company: "Apple",
    datePosted: "6 days ago",
    title: "iOS Developer",
    type: "Internship",
    level: "Entry Level",
    salary: "$30/hr",
    location: "Chennai, India",
  },
  {
    id: 7,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg",
    company: "Spotify",
    datePosted: "7 days ago",
    title: "Audio ML Engineer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$130/hr",
    location: "Remote",
  },
  {
    id: 8,
    logo: "https://logosmarcas.net/wp-content/uploads/2020/11/Tesla-Logo.png",
    company: "Tesla",
    datePosted: "2 days ago",
    title: "Data Analyst",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$90/hr",
    location: "Delhi, India",
  },
  {
    id: 9,
    logo: "https://tse4.mm.bing.net/th/id/OIP.RH6B5bA4OtV54kFaybVENgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    company: "Flipkart",
    datePosted: "3 days ago",
    title: "DevOps Engineer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$105/hr",
    location: "Gurugram, India",
  },
  {
    id: 10,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/75/Zomato_logo.png",
    company: "Zomato",
    datePosted: "1 day ago",
    title: "UI Developer",
    type: "Contract",
    level: "Mid Level",
    salary: "$85/hr",
    location: "Kolkata, India",
  },
];

export default jobs
